adblock detect: "(Anty-adblock|adblock)"
reklama: "Reklama"
kryptokoparki: "Wydobywanie kryptowalut"
cookies: "(Komunikat dot. ciasteczek i polityki prywatności\/RODO|ciasteczka|rodo)"
social filters: "(Element społecznościowy|social)"
hosts file: "Pi-hole, hosts i spółka"
błąd: "Błąd"
pytanie: "Pytanie"
