name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: '@MajkiIT To zgłoszenie zostało oznaczone jako nieaktualne, ponieważ nie było żadnej aktywności przez 60 dni. Usuń etykietę lub napisz komentarz, bo w przeciwnym wypadku zostanie ono zamknięte w ciągu 14 dni.'
          stale-issue-label: 'odrzucone'
          exempt-issue-labels: 'ToDo,do przemyślenia,dodać'
          close-issue-message: 'To zgłoszenie zostało zamknięte, ponieważ minęło 14 dni odkąd została mu nadana etykieta i w tym czasie nie było żadnej aktywności.'
          days-before-issue-stale: 60
          days-before-issue-close: 14
